version: '3.8'

services:
  synapse:
    container_name: synapse 
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_SERVER_NAME=$DOMAIN
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.$SERVICE.rule=Host(`$DOMAIN`)
      - traefik.http.services.$SERVICE.loadbalancer.server.port=$HTTP_PORT
      - traefik.http.routers.$SERVICE.entrypoints=websecure
      - traefik.http.routers.$SERVICE.tls.certresolver=letsencrypt
    volumes:
      - synapse:/data

networks:
  traefik:
    external: true 

volumes:
  synapse:
    name: synapse