version: "3.8"
services:
  adguard:
    container_name: ${SERVICE}
    image: 
    restart: unless-stopped
    ports:
      -
    volumes:
      -
    networks:
      - 
    labels:
      - 
    environment:
      TZ: ${TZ}

volumes:

networks:
