version: '3.8'

services:
  APP_NAME:
    container_name: 
    image: 
    restart: unless-stopped
    environment:
      - 
    networks:
      - 

networks:
  NETWORK_NAME:
    name: 

volumes:
  VOLUME_NAME:
    name: VOLUME_NAME