services:
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: ${SERVICE}
    environment:
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    ports:
      - ${INT_PORT:-0}:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - data:/var/www/onlyoffice/Data
       - log:/var/log/onlyoffice
       - lib:/var/lib/onlyoffice
       - fonts:/usr/share/fonts
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}

    networks:
      - traefik

volumes:
  data:
  log:
  lib:
  fonts:

networks:
  traefik:
    external: true