# docker run -it -p 8444:8444 -p 8443:8443 -v /path/to/your/data/:/tmp/pelican --name=pelican-origin hub.opensciencegrid.org/pelican_platform/origin:latest serve -v /tmp/pelican:/foo/bar -f <federation>
services:
  pelican:
    container_name: ${SERVICE}
    image: hub.opensciencegrid.org/pelican_platform/origin:latest
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - /
    networks:
      - 
    labels:
      - 
    environment:
      -
    command:
      - serve

volumes:

networks:
