services:
  keycloak:
    container_name: ${SERVICE:-keycloak}
    image: quay.io/keycloak/keycloak:26.0.5
    restart: unless-stopped
    ports:
      - ${INT_PORT:-0}:8080
    volumes:
      - data:/opt/keycloak
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
      - keycloack
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE}.rule=Host(${TRAEFIK_DOMAINS})
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - KC_DB_USERNAME=${MYSQL_USER}
      - KC_DB_PASSWORD=${MYSQL_PASSWORD}
      - KC_FEATURES=${KC_FEATURES}
      - KC_HEALTH_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=${DOMAIN}
    command: start
  db:
    container_name: ${SERVICE:-keycloak}-db
    image: mysql:${VERSION:-lts}
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - keycloack
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-keycloack}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  data:
    driver: local
  db:
    driver: local

networks:
  traefik:
    external: true
  keycloack:
    name: keycloack
