services:
  cryptgeon:
    container_name: ${SERVICE:-cryptgeon}
    image: cupcakearmy/cryptgeon:latest
    restart: unless-stopped
    ports:
      - ${INT_PORT:-0}:8000
    networks:
      - traefik
      - cryptgeon
    volumes:
      # Timesync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
      - traefik.docker.network=traefik
    environment:
      # Size limit for a single note.
      - SIZE_LIMIT=4 MiB
      - REDIS=redis://cryptgeon-redis:6379/0
      - MAX_VIEWS=${MAX_VIEWS}
      - MAX_EXPIRATION=${MAX_EXPIRATION}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/live/"]
      interval: 1m
      timeout: 3s
      retries: 2
      start_period: 5s
    depends_on:
      - cryptgeon-redis

  redis:
    container_name: ${SERVICE}-redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cryptgeon

volumes:
   redis:
     driver: local

networks:
  traefik:
    external: true
  cryptgeon:
    name: cryptgeon