version: '3.8'
services:
  homeassistant:
    hostname: ${HOSTNAME}
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - /container/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`${HOSTNAME}`)"
    restart: unless-stopped
    privileged: true
    networks:
      - traefik

networks:
  traefik:
    name: traefik