version: "3.8"
services:
  homeassistant:
    hostname: ${HOSTNAME}
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - /usr/share/container/home-assistant/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    #labels:
    #  - traefik.http.routers.home-assistant.rule=Host(`${HOSTNAME}`)
    env_file:
      - ./.env
    networks:
      - reverse-proxy
    privileged: true
    
networks:
  reverse-proxy:
    name: reverse-proxy