persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883 0.0.0.0
allow_anonymous true

cafile /mosquitto/data/certs/mosquitto-ca.crt
certfile /mosquitto/data/certs/mosquitto-serv.crt
keyfile /mosquitto/data/certs/mosquitto-serv.key