version: "3.8"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 25565:25565
      - 25565:25565/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.routers.${SERVICE}.service=api@internal
      - traefik.http.routers.${SERVICE}.middlewares=strip
      - traefik.http.middlewares.strip.stripprefix.prefixes=/traefik
      - traefik.http.routers.api.middlewares=authelia@docker
      - traefik.http.routers.${SERVICE}.middlewares=authelia@docker
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${TRAEFIK_PORT}
    environment:
      - TZ=Europe/Berlin
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
    command:
      - --log.level=${LOG_LEVEL}
      - --providers.docker=true
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=$ACME_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # http
      - --entrypoints.http.address=:${HTTP_PORT}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      # https
      - --entrypoints.https.address=:${HTTPS_PORT}
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      # minecraft
      - --entrypoints.minecraft.address=:${MINECRAFT_PORT}
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN}

volumes:
  letsencrypt:
    driver: local

networks:
  traefik:
    name: traefik
