version: "3.8"

services:
  traefik:
    hostname: ${CONTAINER_HOSTNAME}
    container_name: traefik
    image: traefik:v2.6
    restart: always
    env_file:
      - ./.env
    ports:
      - 8443:443
      - 8081:8080
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.https.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=${CLOUDFLARE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    labels:
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.rule=Host(`${CONTAINER_HOSTNAME}`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /container/traefik/certs:/letsencrypt
    networks:
      - traefik

networks:
  traefik:
    name: traefik
