version: "3.8"
services:
  nextcloud-db:
    container_name: ${SERVICE}-db
    image: mariadb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - nextcloud_database:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb_read_only_compressed=OFF

  nextcloud-redis:
    container_name: ${SERVICE}-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - nextcloud
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud-app:
    container_name: ${SERVICE}-app
    image: nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud_app:/var/www/html
      - nextcloud_data:/var/www/html/data
    networks:
      - traefik
      - nextcloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
    environment:
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://${DOMAIN}
      OVERWRITEHOST: ${DOMAIN}
      REDIS_HOST: ${SERVICE}-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - ${SERVICE}-db
      - ${SERVICE}-redis

networks:
  traefik:
    external: true
  nextcloud:
    external: true

volumes:
  nextcloud_database:
    name: nextcloud_database
