services:
  onetimesecret:
    container_name: ${SERVICE:-onetimesecret}
    image: onetimesecret/onetimesecret:latest
    restart: unless-stopped
    ports:
      - ${INT_PORT}:3000
    volumes:
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
      - onetimesecret
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
      - traefik.docker.network=traefik
    environment:
      - REDIS_URL=redis://onetimesecret-redis:6379/0
      - COLONEL=${COLONEL}
      - HOST=${DOMAIN}
      - SSL=false
      - RACK_ENV=production

  onetimesecret-redis:
    container_name: ${SERVICE}-redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
      - onetimesecret

volumes:
   redis:
     driver: local

networks:
  traefik:
    external: true
  onetimesecret:
    name: onetimesecret
