version: '3.2'

services:
  postgresql:
    container_name: authentik_postgresql
    hostname: authentik_postgresql
    image: postgres:12-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - authentik_postgresql:/var/lib/postgresql/data
    networks:
      - authentik

  redis:
    container_name: authentik_redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - authentik

  server:
    image: ghcr.io/goauthentik/server
    container_name: authentik
    restart: unless-stopped
    command: server
    env_file:
      - .env
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
      AUTHENTIK_POSTGRESQL__USER: password
      AUTHENTIK_POSTGRESQL__NAME: password
      AUTHENTIK_POSTGRESQL__PASSWORD: password
      AUTHENTIK_SECRET_KEY: omegalul
      # AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      - authentik
      - traefik

  worker:
    image: ghcr.io/goauthentik/server
    container_name: authentik_worker
    restart: unless-stopped
    command: worker
    env_file:
      - .env
    user: root
    volumes:
      - authentik_certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - authentik

networks:
  traefik:
    external: true
  authentik:
    name: authentik
    
volumes:
  authentik_postgresql:
    driver: local
    name: authentik_postgresql
  authentik_certs:
    driver: local
    name: authentik_certs