version: "3.8"
services:
  homeassistant:
    container_name: ${SERVICE}
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
    # networks:
    #   - traefik
    ports:
      - 8123:8123
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
    privileged: true

volumes:
  config:
    driver: local
    
# networks:
#   traefik:
#     external: true
