services:
  telegraf:
    container_name: ${SERVICE}
    image: telegraf:alpine
    volumes:
      - data:/etc/telegraf
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - influxdb
    environment:
      - TZ=${TZ}
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_HOST=${INFLUX_HOST}
      - INFLUX_ORG=${INFLUX_ORG}
    user: telegraf:988

volumes:
  data:
    driver: local

networks:
  influxdb:
    external: true
