services:
  grist:
    image: gristlabs/grist:latest
    container_name: ${SERVICE}
    ports:
      - ${INT_PORT:-0}:8484
    volumes:
      - data:/persist
    restart: unless-stopped
    environment: 
      GRIST_SESSION_SECRET: ${SESSION_SECRET}
      GRIST_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      # OIDC
      GRIST_OIDC_IDP_ISSUER: ${GRIST_OIDC_IDP_ISSUER}
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_IDP_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_IDP_CLIENT_SECRET}
      GRIST_OIDC_SP_HOST: ${GRIST_OIDC_SP_HOST}
      GRIST_IN_SERVICE: ${GRIST_IN_SERVICE}
      GRIST_OIDC_IDP_SCOPES: openid profile email
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
    networks:
      - traefik

volumes:
  data:

networks:
  traefik:
    external: true