version: "3.8"
services:
  adguard:
    container_name: ${SERVICE}
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53
      - 53:53/udp
      - 3000:3000
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${SERVICE}.middlewares=authelia@docker
    environment:
      TZ: ${TZ}

volumes:
  work:
    driver: local
  conf:
    driver: local

networks:
  traefik:
    name: traefik
