version: '3.8'

services:
  nodered:
    container_name: nodered 
    image: nodered/node-red
    restart: unless-stopped
    volumes:
      - nodered:/data
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.$SERVICE.rule=Host(`$DOMAIN`)
      - traefik.http.services.$SERVICE.loadbalancer.server.port=$HTTP_PORT
      - traefik.http.routers.$SERVICE.entrypoints=websecure
      - traefik.http.routers.$SERVICE.tls.certresolver=letsencrypt

networks:
  traefik:
    name: traefik

volumes:
  nodered:
    name: nodered
