services:
  # VPN
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - ${QBITTORRENT_WEBUI_PORT}:8080/tcp # qbittorrent webui port
      - ${QBITTORRENT_TORRENT_PORT_TCP}:6881/tcp # qbittorrent torrent port tcp
      - ${QBITTORRENT_TORRENT_PORT_UDP}:6881/udp # qbittorrent torrent port udp
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
    volumes:
      - gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN

volumes:
  gluetun:
    driver: local
