services:
  home-assistant:
    container_name: ${SERVICE:-home-assistant}
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - config:/config
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
       - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE:-heimdall}.middlewares=local-ipallowlist@docker
    privileged: true

volumes:
  config:
    driver: local
    
networks:
  traefik:
    external: true
