services:
  home-assistant:
    container_name: ${SERVICE:-home-assistant}
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - config:/config
      - /run/dbus:/run/dbus:ro
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
       - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE:-home-assistant}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE:-home-assistant}.entrypoints=https
      - traefik.http.routers.${SERVICE:-home-assistant}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE:-home-assistant}.loadbalancer.server.port=${PORT}
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE:-home-assistant}.middlewares=local-ipallowlist@docker
    privileged: true

volumes:
  config:
    driver: local
    
networks:
  traefik:
    external: true
