services:
  crowdsec:
    container_name: ${SERVICE:-crowdsec}
    image: crowdsecurity/crowdsec:${VERSION:-latest}
    restart: always
    volumes:
      - config:/etc/crowdsec
      - data:/var/lib/crowdsec/data
      # logs
      - traefik_logs:/var/log/traefik:ro
      # Timesync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - traefik.enable=false
    environment: 
      # https://hub.crowdsec.net/author/crowdsecurity/collections/traefik
      COLLECTIONS: ${COLLECTIONS:-crowdsecurity/traefik}
      GID: ${GID-1000}

volumes:
  config:
    driver: local
  data:
    driver: local
  traefik_logs:
    external: true

networks:
  traefik:
    external: true
