services:
  crowdsec:
    container_name: ${SERVICE:-crowdsec}
    image: crowdsecurity/crowdsec:${VERSION:-latest}
    restart: always
    environment: 
      #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
      COLLECTIONS: crowdsecurity/traefik
      GID: ${GID-1000}
    volumes:
      - config:/etc/crowdsec
      - data:/var/lib/crowdsec/data
      - /var/log:/var/log:ro
    networks:
      - crowdsec

  # dashboard:
  #   #we're using a custom Dockerfile so that metabase pops with pre-configured dashboards
  #   build: ./crowdsec/dashboard
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   environment:
  #     MB_DB_FILE: /data/metabase.db
  #     MGID: "${GID-1000}"
  #   depends_on:
  #     - 'crowdsec'
  #   volumes:
  #     - crowdsec-db:/metabase-data/
  #   networks:
  #     crowdsec_test:
  #       ipv4_address: 172.20.0.5

volumes:
  config:
    driver: local
  data:
    driver: local

networks:
  crowdsec:
    name: crowdsec
