version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: unless-stopped
    container_name: ${SERVICE}
    environment:
      MEMORYSIZE: "4G"
      PAPERMC_FLAGS: ""
    volumes:
      - data:/data:rw
    ports:
     - 25565:25565
    stdin_open: true
    tty: true
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DYNMAP_DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${DYNMAP_PORT}
    
volumes:
  data:
    driver: local
  
networks:
  traefik:
    external: true
