version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: always
    container_name: ${SERVICE}
    environment:
      MEMORYSIZE: "4G"
      PAPERMC_FLAGS: ""
    volumes:
      - data:/data:rw
    ports:
     - "25565:25565"
    stdin_open: true
    tty: true
    networks:
      - minecraft
    
volumes:
  data:
    driver: local
  
networks:
  minecraft:
    external: true
