services:
  cloudflare-ddns:
    container_name: ${SERVICE}
    image: favonia/cloudflare-ddns:1
    restart: always
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true]
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
        # Your Cloudflare API token
      - IP4_DOMAINS=${DOMAINS}
        # Your domains (separated by commas)
      - PROXIED=false
        # Leaning toward using Cloudflare's proxy for these domains (optional)
        # Existing DNS records in Cloudflare keep their current proxy statuses