services:
  cloudflare-ddns:
    container_name: ${SERVICE}
    image: favonia/cloudflare-ddns:1
    restart: always
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - IP4_DOMAINS=${DOMAINS}
      - PROXIED=false
    labels:
      - traefik.enable=false