version: "3.8"

services:
  gluetun:
    container_name: ${SERVICE}
    image: qmcgaw/gluetun
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - SHADOWSOCKS=${SHADOWSOCKS}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - OWNED_ONLY=${OWNED_ONLY}
      - TZ=${TZ}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

volumes:
  data:
    driver: local
