services: 
  gluetun:
    container_name: ${SERVICE}-gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}/tcp # qbittorrent webui port
      - ${QBITTORRENT_TORRENT_PORT_TCP}:${QBITTORRENT_TORRENT_PORT_TCP}/tcp # qbittorrent torrent port tcp
      - ${QBITTORRENT_TORRENT_PORT_UDP}:${QBITTORRENT_TORRENT_PORT_TCP}/udp # qbittorrent torrent port udp
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
    volumes:
      - gluetun:/gluetun
      # Timesync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${QBITTORRENT_TORRENT_PORT_TCP}
      - traefik.http.routers.${SERVICE}.middlewares=local-ipallowlist@docker
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN

  exatorrent:
    container_name: ${SERVICE}-exatorrent
    image: ghcr.io/varbhat/exatorrent:latest
    restart: unless-stopped
    ports:
      - 42069:42069
      - ${INT_PORT:-0}:5000
    volumes:
      - ${MEDIA_PATH}:/exa/exadir
      # Timesync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: ${TZ}
    network_mode: service:gluetun


volumes:
  gluetun:
    driver: local
