services:
  uptime-kuma:
    container_name: ${SERVICE}
    image: louislam/uptime-kuma
    restart: unless-stopped
    ports:
      - ${INT_PORT}:3001
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      # Timesync
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${SERVICE}.middlewares=local-ipallowlist@docker

volumes:
  data:
    driver: local
    
networks:
  traefik:
    external: true
