services:
  traefik:
    container_name: traefik
    image: traefik:v3.2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE}.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${SERVICE}.entrypoints=https
      - traefik.http.routers.${SERVICE}.tls.certresolver=letsencrypt
      - traefik.http.routers.${SERVICE}.service=api@internal
      - traefik.http.routers.${SERVICE}.middlewares=strip
      - traefik.http.middlewares.strip.stripprefix.prefixes=/traefik
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=8080
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_TOKEN}
    command:
      - --log.level=${LOG_LEVEL}
      - --providers.docker=true
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # http
      - --entrypoints.http.address=:${HTTP_PORT}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      # https
      - --entrypoints.https.address=:${HTTPS_PORT}
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.http.tls=true
      - --entrypoints.https.http.tls.certResolver=letsencrypt
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN0}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN0}
      - --entrypoints.https.http.tls.domains[1].main=${DOMAIN1}
      - --entrypoints.https.http.tls.domains[1].sans=*.${DOMAIN1}

volumes:
  letsencrypt:
    driver: local

networks:
  traefik:
    name: traefik
